# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
darklua = "seaofvoices/darklua@0.14.1"
rojo = "rojo-rbx/rojo@7.4.4"
StyLua = "JohnnyMorganz/StyLua@2.0.2"
selene = "Kampfkarren/selene@0.27.1"
